### ISSUE TITLE
Professional school hashmap or smth for catName

### ISSUE THREAD

**Issue by JaakkoLipp** [JaakkoLipp/Ammattikissat#29]
if (catStorageList.get(position) instanceof ElectricianMan){
                    message = "Valittu Kissa: Sähkökissa";
                } else if (catStorageList.get(position) instanceof PipeMan) {
                    message = "Valittu Kissa: LVI-Kissa";
                } else if (catStorageList.get(position) instanceof CarMan) {
                    message = "Valittu Kissa: Autokissa";
                } else if (catStorageList.get(position) instanceof LogisticsMan) {
                    message = "Valittu Kissa: Logistiikkakissa";
                } else if (catStorageList.get(position) instanceof RaksaMan) {
                    message = "Valittu Kissa: Raksakissa";
                    holder.catPic.setImageResource(R.drawable.raksakissa_nobg);
                } else {
                    message = "Valittu Kissa: TöiKissa";
                }

**Comment by RoniSeppala** [comment]
this problem solved itself
